apiVersion: apps/v1
kind: Deployment
metadata:
  name: bamboo
  labels:
    app: bamboo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bamboo
  template:
    metadata:
      labels:
        app: bamboo
    spec:
      containers:
      - name: bamboo
        image: atlassian/bamboo-server:latest
        ports:
        - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: bamboo
spec:
  selector:
    app: bamboo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8085
  type: LoadBalancer
